### ISSUE TITLE
Remediation rules do not align with parameters for DLP 

### ISSUE THREAD

**Issue by JamesHeathcote** [OfficeDev/MCCA#15]
MCCA Personally Identifiable Information
Contains IBAN
Contains UK Tax

MCCA Sensitive Financial Information
Contains Azure Storage Account Key

**Comment by karashah1** [comment]
Hey James,

Thanks for writing in! 

Could you please clarify and/or add more details around what is the discrepancy that you are reporting?

**Comment by NehavPandey** [comment]
Hey James , We will updating the SIT mappings in next release.

**Comment by NehavPandey** [comment]
Hey James . We have updated the SIT mappings on the repo and in process of testing before we release to powershell . Can you validate if you are good with version on the GIT hub?

**Comment by NehavPandey** [comment]
Released with MCCA Preview 1.5 https://www.powershellgallery.com/packages/MCCAPreview/1.5
