### ISSUE TITLE
Closing of PS Sessions on exit

### ISSUE THREAD

**Issue by damianscoles** [OfficeDev/MCCA#16]
While I understand the need to close PowerShell sessions to clean up loose ends and all, but I would rather this not be built into a PowerShell module that could be executed as part of a larger script.  Can this option be removed or added as a switch possibly?  The ORCA script, of which the MCCA is very similar to, does not close sessions on exit, so I was surprised when a script I used to call MCCA and ORCA would fail post MCCA.  I figured it was a timeout with the service, when apparently it was MCCA closing my sessions without asking or promoting.  Thank you.

**Comment by NehavPandey** [comment]
Hi .. This is one of the Microsoft security review requirements to close all sessions. In case you do not want to you may go and edit MCCA.psm1 in your local powershell module and comment line#1185
        #Disconnect-ExchangeOnline -Confirm:$false -ErrorAction:SilentlyContinue
This would ensure the session does not get disconnected.
