### ISSUE TITLE
There was an issue in fetching Insider Risk Management information

### ISSUE THREAD

**Issue by tinojr** [OfficeDev/MCCA#27]
Looks like something didn't load correctly? I installed MCCAPreview module 1.5 and ran Get-MCCAReport. It asked for my UPN and i am global admin.

The console says this error: 
03/26/2021 11:16:52 Getting Insider Risk Management Settings
Error:03/26/2021 11:16:52 There was an issue in fetching Insider Risk Management information. Please try running the tool again after some time.

But the log says this error: 
03/26/2021 11:16:52 INFO: Getting Insider Risk Management Settings
03/26/2021 11:16:52 ERROR: The term 'Get-InsiderRiskPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
TRACE: at Get-InsiderRiskManagementSettings, C:\Program Files\WindowsPowerShell\Modules\MCCAPreview\1.5\MCCA.psm1: line 764
at Get-MCCACollection, C:\Program Files\WindowsPowerShell\Modules\MCCAPreview\1.5\MCCA.psm1: line 965
at Invoke-MCCA, C:\Program Files\WindowsPowerShell\Modules\MCCAPreview\1.5\MCCA.psm1: line 1229
at Get-MCCAReport, C:\Program Files\WindowsPowerShell\Modules\MCCAPreview\1.5\MCCA.psm1: line 1159
at <ScriptBlock>, <No file>: line 1

**Comment by NehavPandey** [comment]
@tinojr IRM settings are avialble to IRM Admins. Please validate that you have IR M Admin role.  Let us know if you still get this error?

**Comment by NehavPandey** [comment]
Closing the thread since there is no comment . Please reopen issue if it still persists
