### ISSUE TITLE
typo in check-IP101.ps1 line 70

### ISSUE THREAD

**Issue by SoylenHolger** [OfficeDev/MCCA#31]
same as title, in "check-IP101.ps1" line 70:

            $LabelAssociation = Get-LableCalssification -LogFile $LogFile
should probably read as
            $LabelAssociation = Get-LableClassification -LogFile $LogFile

**Comment by NehavPandey** [comment]
Thanks for pointing out a typo. Since it was user defined function no functionality was impacted as the same was used in function name. We have corrected the typo and merged a new code.

**Comment by NehavPandey** [comment]
Closed
