### ISSUE TITLE
Issue while accessing improvement actions via the report

### ISSUE THREAD

**Issue by kunalkankariya** [OfficeDev/MCCA#4]
### Version 1.2

Improvement actions accessed via the report throw an error

> Request: /apiproxy/stp/cmdata/complianceScore?$filter=Solution%20eq%20'Information%20protection'%20and%20Status%20eq%20'None%2CNotAssessed%2CPassed%2CFailedLowRisk%2CFailedMediumRisk%2CFailedHighRisk%2COutOfscope%2CToBeDetermined%2CCouldNotBeDetermined%2CPartiallyTested%2CSelect'%20and%20ControlType%20eq%20'CustomerManagedControl%2CCustomControl'&$top=1
> Status code: 500
> Diagnostic information: {Version:17.00.5515.008,Environment:SEAPROD,DeploymentId:757b444cc3f54ab8b1ff93b3b9aa9728,InstanceId:WebRole_IN_1,SID:fb91b1f9-360e-4531-b1ca-aa16e817d3f1,CID:9cdf8ebe-a4bb-488c-89c6-f35cffeaa106}
> Time: Tue, 20 Oct 2020 05:37:48 GMT
> 

This is possibly because of the query string used to filter improvement actions. "Outofscope" isn't a valid filter. It should be "NotInScope".

Thanks!

**Comment by karashah1** [comment]
We have now updated the links with new release of v1.3 of our PowerShell module!
Thanks for reporting this 👍
