### ISSUE TITLE
Improvement Dropdown does not expand

### ISSUE THREAD

**Issue by gojo119** [OfficeDev/MCCA#42]
I really appreciate your awesome tool.
There is one point what is currently not working (at least for me)
The dropdown next to the improvement label doesn't do anything (at least for me) and I assume it should show additional information to the issues found (https://docs.microsoft.com/en-us/microsoft-365/compliance/compliance-manager-mcca?view=o365-worldwide#:~:text=Select%20the%20dropdown,and%20relevant%20documentation.). 
I tried it in several different browsers (Edge, Chrome, Firefox).
In the HTML markup the quick summary is there but somehow it seems that my browsers don't expand the dropdown accordingly.

I updated to version 1.7 but the issue could be reproduced in an older version too.

**Comment by karashah1** [comment]
Hey @gojo119 

Can you share the screenshots of what is happening for you? Ideally, on clicking the downward arrow, a section should drop down with additional details.

It may be worthwhile to meet and diagnose this issue. Drop us an email at mccahelp@microsoft.com and we will set something up to resolve this.

:)

**Comment by gojo119** [comment]
Hello @karashah1,

thank you for your reply.

I attached a screenshot of a current output
![Webaufnahme_29-3-2022_1402_](https://user-images.githubusercontent.com/10562860/160606834-bc51b45b-6c00-45bc-859e-f4562f63334c.jpeg)

If you prefer, I can send you an email to [mccahelp@microsoft.com](mailto:mccahelp@microsoft.com) as well. 

best regards
Gottfried

**Comment by gojo119** [comment]
Hi,

it seems to be a network related issue on my client, therefore I closed this issue.

br
Gottfried
