### ISSUE TITLE
Unable to execute MCCA after install

### ISSUE THREAD

**Issue by airdalle** [OfficeDev/MCCA#5]
Hi
There's something I didn't understand in how to use this great tool, but I don't manage to run it.
I succesfully installed it but then when I run Get-MCCAReport cmdlet, this is what happen. see screenshot below.
Can you provide some guidance ? thank you
![image](https://user-images.githubusercontent.com/36157179/96879347-3a353d80-147c-11eb-9e29-58eb343cd24d.png)

Romain

**Comment by karashah1** [comment]
Hello airdalle,

Based on the screenshot you shared, you don't seem to have Exchange Online Management module (v2.0.3 or higher) installed. It is one of the pre-requisites as mentioned here [https://github.com/OfficeDev/MCCA]

Please run the following cmdlet first
`Install-Module -Name ExchangeOnlineManagement` 

Then try running the `Get-MCCAReport` cmdlet and it should work fine.

Hopefully this should solve the error you are facing.

Let us know if this solution works for you or not.

**Comment by airdalle** [comment]
Thank you very much. That was it. I read too fast the prerequisite section :-|. it works like a charm now !

**Comment by airdalle** [comment]
Adding one question : when running the cmdlet, the following warning has been displayed in the console. Is it possible in the next release to have more details on this ?
![image](https://user-images.githubusercontent.com/36157179/96973396-20493880-1518-11eb-809d-db60beacbfb1.png)

**Comment by karashah1** [comment]
Yes airdalle, feedback taken & we will work on adding more information for errors & warnings in future versions.

Could you share a screenshot or copy paste the errors that showed up during execution for you?

We will try to provide a quick-fix (if possible) for now.

**Comment by airdalle** [comment]
Actually, excepted this message, it seems like that no errors were met, so this warning message is kind of confusing. see below : 
![image](https://user-images.githubusercontent.com/36157179/96974626-c9446300-1519-11eb-9713-d71fcd1b04ab.png)

**Comment by NehavPandey** [comment]
@airdalle This is a generalized message that is shown in case we ran into some technical issues while generating the report. The tool would also have generated a log file at C:\Users\rdalle\AppData\Local\Microsoft\MCCA\Logs\ with the same name as your report. The log should guide you to the exact issue that happened. Let us know if that helps.
